export const BUSINESS_SUCCESS = "BUSINESS_SUCCESS";
export const BUSINESS_FETCH_ERROR = "BUSINESS_FETCH_ERROR";

export const HEALTH_SUCCESS = "HEALTH_SUCCESS";
export const HEALTH_FETCH_ERROR = "HEALTH_FETCH_ERROR";

export const HOME_SUCCESS = "HOME_SUCCESS";
export const HOME_FETCH_ERROR = "HOME_FETCH_ERROR";

export const SCIENCE_SUCCESS = "SCIENCE_SUCCESS";
export const SCIENCE_FETCH_ERROR = "SCIENCE_FETCH_ERROR";

export const SPORTS_SUCCESS = "SPROTS_SUCCESS";
export const SPORTS_FETCH_ERROR = "SPORTS_FETCH_ERROR";

export const TECH_SUCCESS = "TECH_SUCCESS";
export const TECH_FETCH_ERROR = "TECH_FETCH_ERROR";

export const WORLD_SUCCESS = "WORLD_SUCCESS";
export const WORLD_FETCH_ERROR = "WORLD_FETCH_ERROR";
